---
title: "ESM 204 HW 3: Distributional consequences of climate policy"
author: "Bri Baker and Anna Talken"
date: "Spring 2021"
output:
  html_document:
    theme: cosmo
    highlight: kate
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      message = FALSE,
                      warning = FALSE)
library(tidyverse)
library(here)
library(janitor)
```

## Data Setup
```{r}
gas <- read_csv(here("HW3_data.csv")) %>% 
  clean_names() %>% 
  mutate(q_agg_gal = q_low_gallons + q_high_gallons)

gas_price <- 3 # $/gal
scc_ton <- 51 # $/metric ton
ton <- 2000 # lb

scc_lb <- scc_ton/ton

```

## Question 1
```{r}
emission_gal <- 19.6 # pounds of co2 in a gallon of gas

mec <- emission_gal*scc_lb

```

The marginal external cost is $`r mec`/gal.


## Question 2

```{r demand curve}
d_agg <- lm(price_dollars ~ q_agg_gal, data = gas) #create linear model

d_agg_slope <- d_agg$coefficients[[2]] #finds the slope
d_agg_intercept <- d_agg$coefficients[[1]] #finds the intercept

demand <- function(q, model){
  p <- model$coefficients[[1]] + model$coefficients[[2]]*q
return(p)
}

inverse_demand <- function(p, model){
  q <- (p - model$coefficients[[1]])/model$coefficients[[2]]
  return(q)
}

```

Aggregate demand: p = `r d_agg_slope`q + `r d_agg_intercept`

```{r supply curve}
s_slope <- (3)/(demand(3, d_agg))

s_intercept <- 0
```

```{r}
# Plotting demand and supply curves

#DEMAND CURVE
d_ag <- lm(price_dollars ~ q_agg_gal, data = gas) #create linear model

d_ag_slope <- d_ag$coefficients[[2]] #finds the slope
d_ag_intercept <- d_ag$coefficients[[1]] #finds the intercept

price_fitted <- d_ag_intercept + d_ag_slope*gas$q_agg_gal #creates estimated line

aggregate_demand <- ggplot(data=gas, aes(x=q_agg_gal,y=price_dollars))+
  geom_point() +
  theme_minimal()+
  labs(x = "Quantity of gas demanded (gal)",
       y = "Price ($/gal)",
       title = "Aggregate demand for gasoline using linear regression") +
  geom_line(aes(y=price_fitted, x=q_agg_gal)) #plotted the fitted relationship on the graph

```

Aggregate supply: p = `r s_slope`q

```{r surplus initial}

surplus_p <- function(p, model){
  q <- inverse_demand(p, model)
  cs <- 0.5*(model$coefficients[[1]] - p)*q
  return(cs)
}

surplus_q <- function(q, model){
  p <- demand(q, model)
  cs <- 0.5*(model$coefficients[[1]] - p)*q
  return(cs)
}

cs_initial <- surplus_p(3, d_agg)

ps_initial <- 0.5*(3*inverse_demand(3, d_agg))

```

###FIX SCIENTIFIC NOTATION
Consumer "benefit": $`r round(cs_initial, 2)`
Producer "benefit": $`r round (ps_initial, 2)`

```{r env cost initial}
env_costs <- inverse_demand(3, d_agg)*scc_lb
```

Environmental cost: $`r round(env_costs)`
